decals = new Stickers(2, true);
decals.Add(spr_smile, 0, 128, 128);
decals.SetFreeze(false);
//decals.Update();
gpu_set_zwriteenable(true);
gpu_set_ztestenable(true);
gpu_set_alphatestenable(true);
gpu_set_alphatestref(128);
//z = 0;
show_debug_overlay(true);